CREATE DATABASE SYSCAD
GO

CREATE TABLE SYSLOGIN(
IDLOGIN INT NOT NULL IDENTITY(1, 1),
USUARIO VARCHAR(15) NOT NULL,
SENHA VARCHAR(15) NOT NULL,
ADMINISTRADOR BIT);

CREATE TABLE CAD(
IDCAD INT NOT NULL IDENTITY(1, 1),
NOME VARCHAR(30) NOT NULL,
DOCUMENTO VARCHAR(20) NOT NULL,
DESCRICAO VARCHAR(50));